# This workflow will build and test a Swift package for iOS using xcodebuild.
name: Swift Package iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ci
  cancel-in-progress: true
  
jobs:
  ios-latest:
    name: Unit Tests (iOS 17.4, Xcode 15.3)
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          Scripts/test.sh -s "LocoBeeTests" -d "OS=16.4,name=iPhone 14 Pro"
