# This workflow will build and test a Swift package for iOS using xcodebuild.
name: Swift Package iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ci
  cancel-in-progress: true
  
jobs:
  ios-latest:
    name: Unit Tests (iOS 16.4, Xcode 14.3.1)
    runs-on: macOS-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          Scripts/test.sh -s "LocoBeeTests" -d "OS=16.4,name=iPhone 14 Pro"
